name: Build and push to docker hub

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./script-app/web-vote-app
            image: web-vote-app
            file: ./script-app/web-vote-app/Dockerfile
          - context: ./script-app/results-app
            image: results-app
            file: ./script-app/results-app/Dockerfile
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest
          labels: ${{ matrix.image }}

      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://167.172.68.62:8080"
          user: "rezamnr"
          token: ${{ secrets.TOKEN }}
          job: "Deploy-to-swarm"
